---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install  apche2 webserver in ubantu nodes
    apt:
      name: apache2  
      state: present
    when: ansible_os_family =="debian" 

  - name: i want to  start webserver on ubantu nodes
    service:
       name: apache2
       state: restarted 
    when: ansible_os_family =="debian"

  - name: i want to install webserver   on Redhat nodes
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
  - name: i  want to start webserver on RedHat nodes 
   service:  
     name: httpd
     state: started 
    when: ansible_os_family =="RedHat"

       


