---
- hosts: 172.31.25.218
  become: yes
  gather_facts: yes
  tasks:
  - name: i want install apache2 webserver  on ubuntu  nodes
    apt:
      name: "{{mywebpackonubuntu}}" 
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver on ubuntu nodes
    service:
       name: "{{mywebpackonubuntu}}"
       state: started
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on RedHat nodes 
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name:  i want to start webserver on RedHat nodes
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family =="RedHat"
---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want install apache2 webserver  on ubuntu  nodes
    apt:
      name: "{{mywebpackonubuntu}}" 
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver on ubuntu nodes
    service:
       name: "{{mywebpackonubuntu}}"
       state: started
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on RedHat nodes 
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name:  i want to start webserver on RedHat nodes
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family =="RedHat"
---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install  apche2 webserver in ubantu nodes
    apt:
      name: apache2  
      state: present
    when: ansible_os_family =="debian" 

  - name: i want to  start webserver on ubantu nodes
    service:
       name: apache2
       state: started 
    when: ansible_os_family =="debian"

  - name: i want to install webserver   on Redhat nodes
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
  - name: i  want to start webserver on RedHat nodes 
    service:  
      name: httpd
      state: started 
    when: ansible_os_family =="RedHat"

       


