---
- hosts: all
  become: yes
  tasks: 
  -  name: i want to install  apche2 webserver
     apt:
       name: apache2  
       state: present

  -  name: i want to  start webserver
     services:
       name: apache2
       state: restarted